sudo: false
language: python
install: pip install tox-travis
script: tox

matrix:
    include:
        - python: 3.6
          env: TOXENV=flake8
        - python: 3.6
          env: TOXENV=py36
        - python: 2.7
          env: TOXENV=py27
